<?php
/**
 * Meilisearch Autocomplete Category Template
 */
?>
<script type="text/template" id="meilisearch-autocomplete-category-template">
    <div class="meilisearch-autocomplete-category">
        <div class="meilisearch-autocomplete-category-name">
            {{{_highlightResult.name.value}}}
        </div>
        {{#product_count}}
        <div class="meilisearch-autocomplete-category-count">
            ({{product_count}} <?php echo $this->__('products') ?>)
        </div>
        {{/product_count}}
    </div>
</script>