<?php
/**
 * Meilisearch Autocomplete Page Template
 */
?>
<script type="text/template" id="meilisearch-autocomplete-page-template">
    <div class="meilisearch-autocomplete-page">
        <div class="meilisearch-autocomplete-page-name">
            {{{_highlightResult.name.value}}}
        </div>
        {{#_highlightResult.content.value}}
        <div class="meilisearch-autocomplete-page-content">
            {{{_highlightResult.content.value}}}
        </div>
        {{/_highlightResult.content.value}}
    </div>
</script>