<?php
/**
 * Meilisearch Autocomplete Suggestion Template
 */
?>
<script type="text/template" id="meilisearch-autocomplete-suggestion-template">
    <div class="meilisearch-autocomplete-suggestion">
        <div class="meilisearch-autocomplete-suggestion-query">
            {{{_highlightResult.query.value}}}
        </div>
        {{#num_results}}
        <div class="meilisearch-autocomplete-suggestion-count">
            ({{num_results}})
        </div>
        {{/num_results}}
    </div>
</script>